import { useEffect, useMemo, useState } from 'react';
import Chart, { ESTIMATOR_COLORS } from './Chart';
import EstimatorControls from './EstimatorControls';
import EnsembleAudit from './EnsembleAudit';
import { calculateEnsemble, compatibility, selectedEstimators } from './ensemble';
import GapMap from './GapMap';
import Overview from './Overview';
import ProjectionPanel from './ProjectionPanel';
import SimpleStock from './SimpleStock';
import GpuPrices from './GpuMarket';
import HistoryControl from './HistoryControl';
import { projectionCurve, projectionCsv, targetReference, TARGET_REFERENCE_DAYS } from './projection';
import EpsEvaluation from './EpsEvaluation';
import ReportedEarnings from './ReportedEarnings';
import BacktestCoverage from './BacktestCoverage';
import { bandValue, bestSeries, calculate, csvExport, daysBetween, priceVsMedian, splitFactor } from './engine';
import type { Company, DashboardData, Series, Settings, ValuationPoint } from './types';

const DEFAULTS:Settings={company:'sk_hynix',series:'',window:365,display:1826,maxAge:180,strict:false,metric:'price',bands:[1,1.5,2],asOf:'',mode:'single',combine:'median',targetSigma:0,compareWindows:false,compareWindow:90,overviewSort:'universe',overviewVersion:2};
function initialSettings():Settings {
  try {
    const saved=JSON.parse(localStorage.getItem('forward-settings')||'{}'), query=Object.fromEntries(new URLSearchParams(location.search));
    const s={...DEFAULTS,...saved,...query};
    // Older saved views opened the dense comparison layout. Start those in the
    // simple view, then preserve choices made with the new overview.
    const overviewState=query.overviewVersion==='2'?s:saved.overviewVersion===2?{...DEFAULTS,...saved}:DEFAULTS;
    const bounded=(v:unknown,min:number,max:number,fallback:number)=>Number.isFinite(Number(v))?Math.max(min,Math.min(max,Math.round(Number(v)))):fallback;
    return {...DEFAULTS,overviewVersion:2,compareWindows:overviewState.compareWindows===true||overviewState.compareWindows==='true',compareWindow:[90,180,365].includes(Number(s.compareWindow))?Number(s.compareWindow):90,overviewSort:['universe','name','upside'].includes(overviewState.overviewSort)?overviewState.overviewSort:'universe',targetSigma:[-2,-1.5,-1,0,1,1.5,2].includes(Number(s.targetSigma))?Number(s.targetSigma):0,mode:['single','overlay','ensemble'].includes(s.mode)?s.mode:'single',combine:s.combine==='mean'?'mean':'median',estimatorIds:Array.isArray(s.estimatorIds)?s.estimatorIds.filter((v:unknown)=>typeof v==='string'):typeof s.estimatorIds==='string'&&s.estimatorIds!=='auto'?s.estimatorIds.split(',').filter(Boolean):undefined,company:String(s.company),series:String(s.series),window:bounded(s.window,20,2192,365),display:bounded(s.display,0,2192,1826),maxAge:bounded(s.maxAge,30,730,180),strict:s.strict===true||s.strict==='true',metric:'price',bands:(Array.isArray(s.bands)?s.bands:typeof s.bands==='string'?s.bands.split(',').map(Number):[1,1.5,2]).filter((v:number)=>[1,1.5,2].includes(v)),asOf:/^\d{4}-\d{2}-\d{2}$/.test(s.asOf)&&Number.isFinite(Date.parse(s.asOf+'T00:00:00Z'))?s.asOf:''};
  } catch{return DEFAULTS}
}
const number=(value:number|null|undefined,digits=2)=>value==null||!Number.isFinite(value)?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(value);
const dateLabel=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
function saveFile(filename:string,contents:string,type='text/csv') {const url=URL.createObjectURL(new Blob([contents],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
function Sparkline({company}:{company:Company}) {
  const values=company.prices.slice(-45).map(p=>p.close),min=Math.min(...values),max=Math.max(...values);
  return <svg width="60" height="25" viewBox="0 0 60 25" aria-hidden="true"><polyline fill="none" stroke="currentColor" strokeWidth="1.5" points={values.map((v,i)=>`${i/(values.length-1)*60},${23-(v-min)/(max-min||1)*21}`).join(' ')}/></svg>;
}
function SourceLink({url,label='Original source'}:{url:string;label?:string}) {return /^https?:\/\//.test(url)?<a href={url} target="_blank" rel="noreferrer">{label} ↗</a>:<span>{label} unavailable</span>}

export default function App() {
  const [data,setData]=useState<DashboardData|null>(null),[error,setError]=useState(''),[settings,setSettings]=useState<Settings>(initialSettings),[tab,setTab]=useState(()=>new URLSearchParams(location.search).get('view')==='gpu'?'gpu':'valuation'),[inspected,setInspected]=useState<ValuationPoint|null>(null),[copied,setCopied]=useState(false),[advanced,setAdvanced]=useState(false);
  useEffect(()=>{fetch('/data/dashboard.json').then(r=>{if(!r.ok)throw new Error(`Data returned ${r.status}`);return r.json()}).then((d:DashboardData)=>{if(d.schema_version!==1||!Array.isArray(d.companies)||d.companies.length===0)throw new Error('Dataset format is not supported');setData(d)}).catch(e=>setError(String(e)))},[]);
  useEffect(()=>{localStorage.setItem('forward-settings',JSON.stringify(settings))},[settings]);
  useEffect(()=>{const url=new URL(location.href);if(tab==='gpu')url.searchParams.set('view','gpu');else url.searchParams.delete('view');history.replaceState(null,'',url)},[tab]);
  const company=data?.companies.find(c=>c.id===settings.company)||data?.companies[0];
  const defaultSeries=useMemo(()=>company?bestSeries(settings.mode==='ensemble'?{...company,series:company.series.filter(s=>compatibility(company,s).eligible)}:company,settings.asOf||data?.cutoff||''):undefined,[company,settings.asOf,data?.cutoff,settings.mode]);
  const series=company?.series.find(s=>s.id===settings.series&&(settings.mode!=='ensemble'||compatibility(company,s).eligible))||defaultSeries;
  const asOf=settings.asOf&&data?settings.asOf<data.cutoff?settings.asOf:data.cutoff:data?.cutoff||'';
  const estimators=useMemo(()=>company?selectedEstimators(company,series,settings):[],[company,series,settings.mode,settings.estimatorIds]);
  const points=useMemo(()=>company?(settings.mode==='ensemble'?calculateEnsemble(company,series,estimators,{...settings,asOf},settings.combine):calculate(company,series,{...settings,asOf})):[],[company,series,estimators,settings.mode,settings.combine,settings.window,settings.maxAge,settings.strict,asOf]);
  const overlays=useMemo(()=>settings.mode==='overlay'&&company?estimators.map(s=>({id:s.id,label:s.label,points:calculate(company,s,{...settings,asOf}).filter(p=>!settings.display||daysBetween(asOf,p.date)<=settings.display)})):undefined,[company,estimators,settings.mode,settings.window,settings.maxAge,settings.strict,settings.display,asOf]);
  const visible=useMemo(()=>points.filter(p=>!settings.display||daysBetween(asOf,p.date)<=settings.display),[points,settings.display,asOf]);
  const current=points.at(-1),valid=visible.filter(p=>p.multiple!==null),bandDays=visible.filter(p=>bandValue(p,0,'price')!==null).length;
  const primaryProjection=useMemo(()=>company?projectionCurve(company,targetReference(company,series,{...settings,asOf}),series,{...settings,window:TARGET_REFERENCE_DAYS}):[],[company,series,estimators,settings.mode,settings.combine,settings.maxAge,settings.strict,asOf]);
  const projection=primaryProjection.at(-1)||null;
  const projections=useMemo(()=>{
    if(!company)return [];
    if(settings.mode==='overlay')return estimators.map(s=>{
      const points=projectionCurve(company,targetReference(company,s,{...settings,asOf,mode:'single'}),s,{...settings,window:TARGET_REFERENCE_DAYS});
      return {id:s.id,label:s.label,points};
    });
    return [{id:projection?.id||'primary',label:projection?.label||'',points:primaryProjection}];
  },[settings.mode,estimators,company,primaryProjection,projection,settings.maxAge,settings.strict,asOf]);
  const update=(patch:Partial<Settings>)=>{setSettings(s=>({...s,...(patch.company!==undefined&&patch.company!==s.company||patch.series!==undefined&&patch.series!==s.series?{estimatorIds:undefined}:{}),...patch}));setInspected(null)};
  if(error)return <div className="loading"><h1>The dataset could not be opened.</h1><p>{error}</p><p>Rebuild the local dataset, then reload this page.</p><button onClick={()=>location.reload()}>Try again</button></div>;
  if(!data||!company)return <div className="loading"><span className="wordmark">forward<span> / </span></span><p>Opening the research archive…</p></div>;
  const selected=inspected||current;
  const snapshot=selected?.snapshot;
  const latestReport=series?.snapshots.at(-1);
  const importedNtm=settings.mode!=='ensemble'&&latestReport?.kind==='ntm';
  const observedSnapshot=settings.mode!=='ensemble'&&latestReport?.first_observed_at;
  const viewLabel=settings.mode==='ensemble'?`${settings.combine==='mean'?'Equal-weighted mean':'Median'} combined estimates`:series?.label||'No usable earnings series';
  const chartKey=`${company.id}-${series?.id}-${settings.mode}-${settings.combine}-${estimators.map(s=>s.id).join(',')}-${asOf}-${settings.display}`;
  const exportChart=()=>{
    const contents=overlays?.length?overlays.map((o,i)=>{const csv=csvExport(o.points,company,company.series.find(s=>s.id===o.id),settings);return i?csv.split('\n').slice(1).join('\n'):csv}).join('\n'):csvExport(overlays?calculate(company,undefined,{...settings,asOf}).filter(p=>!settings.display||daysBetween(asOf,p.date)<=settings.display):visible,company,overlays?undefined:series,settings);
    saveFile(`${company.symbol}-${asOf}-${settings.window}d.csv`,contents);
  };
  return <div className={`app-shell ${advanced?'advanced-app':'simple-app'}`}>
    <aside className="sidebar">
      <a href="/" className="wordmark" aria-label="Forward home">forward<span> / </span></a>
      <p className="sidebar-caption">{advanced?'AI VALUATION RESEARCH':'Your stocks, a year ahead.'}</p>
      <div className="universe-heading"><span>{advanced?'OUR UNIVERSE':'STOCKS'}</span><span>{String(data.companies.length).padStart(2,'0')}</span></div>
      <nav aria-label="Company selection">{data.companies.map(c=><button key={c.id} className={`stock-button ${company.id===c.id?'active':''}`} onClick={()=>{update({company:c.id,series:''});setTab('valuation')}} aria-pressed={company.id===c.id}><span className="stock-symbol">{c.symbol}</span><span className="stock-name">{c.name}</span>{advanced&&<><span className="spark"><Sparkline company={c}/></span><span className={`dot ${c.series.length?'has-data':''}`} title={c.series.length?'Partial forecast archive':'Earnings history missing'}/></>}</button>)}</nav>
      {advanced&&<div className="sidebar-note"><span className="small-label">RESEARCH ARCHIVE</span><strong>{data.totals.forecast_observations}</strong><p>extracted observations<br/>{data.totals.broker_pdfs} original broker PDFs</p><button className="text-button" onClick={()=>setTab('coverage')}>Inspect data coverage ↗</button></div>}
      <div className="local-status">Saved prices · {dateLabel(data.cutoff)}</div>
    </aside>
    <main>
      <header className="topbar"><span>{tab==='gpu'?'Compute market':advanced?'Research workspace':'One-year price targets'}</span><div className="top-actions">{advanced&&<button onClick={()=>{const url=new URL(location.href);Object.entries({...settings,series:series?.id||'',bands:settings.bands.join(','),estimatorIds:settings.estimatorIds?.join(',')??'auto'}).forEach(([k,v])=>url.searchParams.set(k,String(v)));navigator.clipboard.writeText(url.toString()).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),1800)})}}>{copied?'Copied':'Copy view link'} ↗</button>}<button className="advanced-toggle" onClick={()=>{setAdvanced(!advanced);if(advanced&&tab!=='overview'&&tab!=='gpu')setTab('valuation')}}>{advanced?'Simple view':'Advanced'}</button></div></header>
      {tab==='gpu'?<section className="page-heading"><div><div className="eyebrow">COMPUTE <span>/</span> RENTAL MARKET <span>/</span> USD</div><h1>GPU rental prices<span className="title-dot">.</span></h1></div></section>:
<section className="page-heading"><div><div className={`eyebrow ${tab==='overview'?'overview-eyebrow':''}`}>{tab==='overview'?`${data.companies.length} COMPANIES`:company.exchange} <span>/</span> {tab==='overview'?'ONE-YEAR TARGETS':company.symbol} <span>/</span> {tab==='overview'?'LISTING CURRENCIES':company.currency}</div><h1>{tab==='overview'?'12-month targets':company.name}<span className="title-dot">.</span></h1>{advanced&&<p>{tab==='overview'?'Every target is one year ahead.':'One-year price targets from future earnings and historical valuation ranges.'}</p>}</div>{advanced&&<div className={`price-heading ${tab==='overview'?'overview-stock-price':''}`}><span className="small-label">{current?`CLOSE · ${dateLabel(current.date)}`:'PRICE HISTORY'}</span><strong>{number(current?.price,company.currency==='KRW'?0:2)} <small>{company.currency}</small></strong><span>Split-adjusted · cash dividends excluded</span></div>}</section>}
      <div className="tabs" role="tablist">{[['valuation',advanced?'Valuation bands':'This stock'],['overview','All stocks'],['gpu','GPU prices'],...(advanced?[['forecasts','Forecast archive'],['outcomes','Forecast vs. actual'],['coverage','Data coverage']]:[])].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
      {tab==='gpu'&&<GpuPrices/>}
      {tab==='valuation'&&company.data_notes?.map((note,i)=><div className="evidence-note" role="note" key={i}><span className="evidence-icon">i</span><p>{note}</p></div>)}
      {tab==='valuation'&&!advanced&&<SimpleStock company={company} points={points} curve={primaryProjection} settings={settings} onChange={update}/>}
      {tab==='valuation'&&advanced&&<>
        <EstimatorControls company={company} anchor={series} settings={settings} onChange={update}/>
        <section className="controls card">
          <label className="series-select" title="Initial series selected for usable current data and historical coverage, not analyst accuracy.">Earnings series<select aria-label="Earnings series" value={series?.id||''} onChange={e=>update({series:e.target.value})}>{company.series.length?company.series.map(s=><option key={s.id} value={s.id} disabled={settings.mode==='ensemble'&&!compatibility(company,s).eligible}>{s.label}</option>):<option value="">Historical earnings feed needed</option>}</select></label>
          <label>Entry window in calendar days<div className="input-with-unit"><input aria-label="Window in days" type="number" min={20} max={2192} value={settings.window} onChange={e=>{const n=Number(e.target.value);if(n>=20&&n<=2192)update({window:n})}}/><span>days</span></div></label>
          <label>As of<input aria-label="As of date" type="date" min="2020-09-10" max={data.cutoff} value={asOf} onChange={e=>{if(e.target.value)update({asOf:e.target.value})}}/></label>
          <div className="preset-row"><span>LOOKBACK</span>{[90,180,365,730,1095,1826].map(n=><button key={n} className={settings.window===n?'selected':''} onClick={()=>update({window:n})}>{n<365?`${n}D`:n===1826?'5Y':`${Math.round(n/365)}Y`}</button>)}</div>
        </section>
        <div className="evidence-note"><span className="evidence-icon">i</span><p>{settings.strict?'Verified availability only. Uses provider timestamps or exact archived reports from their proven availability date. Other report-date assumptions are excluded.':observedSnapshot?'First-observed public snapshot. The collection timestamp is known; the underlying numerical revision date is unknown. The age limit measures time since capture, and the values enter from the next UTC day.':importedNtm?'Provider NTM snapshots. Values enter the chart the day after the availability timestamp supplied in the export.':series?'Dated-report reconstruction. Estimates enter the chart after the printed report date; original publication timing is unverified.':'Historical EPS is missing for this company. The price chart is available; valuation bands need an earnings series.'} {series&&!importedNtm&&'Annual models use a day-weighted FY1/FY2 proxy for next-twelve-month EPS.'}</p><button onClick={()=>setTab('coverage')}>Coverage ↗</button></div>
        {series?.comparability_note&&<div className="evidence-note"><span className="evidence-icon">i</span><p>{series.comparability_note} {series.comparability_source_url&&<SourceLink url={series.comparability_source_url} label="Issuer definition"/>}</p></div>}
        {settings.mode!=='single'&&settings.mode&&<p className="view-caption">{settings.mode==='ensemble'?`${viewLabel} · ${current?.ensemble?.contributors.length||0} current contributors · purple diamonds mark membership changes`:`Headline cards and date details: ${series?.label||'No primary series'}. Chart curves follow the estimator selections above.`}</p>}
        <ProjectionPanel company={company} projection={projection} originProjection={primaryProjection[0]||null} sigma={settings.targetSigma||0} onSigma={targetSigma=>update({targetSigma})} onExport={()=>saveFile(`${company.symbol}-${asOf}-${TARGET_REFERENCE_DAYS}d-target-reference-projections.csv`,projectionCsv(company,projections.flatMap(p=>p.points.length?[p.points.at(-1)!]:[])))}/>
        <section className="chart-card card"><div className="chart-heading"><div><h2>Share price & implied valuation bands</h2><p>Rolling {settings.window}-day reference · {overlays?'Primary series: ':''}{valid.length} / {visible.length} sessions with usable forward P/E · {bandDays} with bands</p></div><span className="small-label">PRICE IN {company.currency}</span></div>
          <div className="chart-toolbar"><div className="legend"><span><i className="legend-price"/>Actual share price</span><span><i className="legend-median"/>Projected bands · 1-year reference</span>{!overlays&&<span><i className="simple-range"/>Historical entry bands</span>}{[1,1.5,2].map(n=><label key={n}><input type="checkbox" checked={settings.bands.includes(n)} onChange={()=>update({bands:settings.bands.includes(n)?settings.bands.filter(v=>v!==n):[...settings.bands,n]})}/> ±{n}σ</label>)}</div><HistoryControl allowAll value={settings.display} onChange={display=>update({display})}/></div>
          {overlays&&<div className="overlay-legend">{overlays.map((o,i)=><span key={o.id}><i style={{background:ESTIMATOR_COLORS[i%ESTIMATOR_COLORS.length]}}/>{o.label}</span>)}{!overlays.length&&<span>Select estimators above to add valuation curves.</span>}</div>}
          {visible.length?<Chart points={visible} metric="price" bands={settings.bands} currency={company.currency} chartKey={chartKey} overlays={overlays} projections={projections} targetSigma={settings.targetSigma||0} onInspect={setInspected}/>:<div className="empty-chart">No price observations are available for this date range.</div>}
          <div className="chart-footer"><span>Drag to zoom · Double-click to reset · Click a historical date to inspect · Future lines are valuation scenarios</span><button className="text-button" onClick={exportChart}>Export chart data ↓</button></div>
        </section>
        {settings.mode==='ensemble'&&<EnsembleAudit company={company} selected={selected} points={visible} onExport={saveFile} onInspect={setInspected}/>}
        <div className="lower-grid"><section className="card detail-card"><div className="section-heading"><h2>{inspected?'Selected date':'Latest observation'}</h2><span>{selected?dateLabel(selected.date):'No prices'}</span></div>{selected&&<><dl><div><dt>Current price vs contemporaneous median</dt><dd>{number(priceVsMedian(selected))}%</dd></div><div><dt>{importedNtm?'Forward EPS':'Forward EPS proxy'}</dt><dd>{number(selected.eps)} {company.currency}</dd></div><div><dt>Median-implied price</dt><dd>{number(bandValue(selected,0,'price'),company.currency==='KRW'?0:2)} {company.currency}</dd></div>{[1,1.5,2].map(sigma=><div key={sigma}><dt>Median ±{sigma}σ</dt><dd>{number(bandValue(selected,-sigma,'price'),company.currency==='KRW'?0:2)} – {number(bandValue(selected,sigma,'price'),company.currency==='KRW'?0:2)}</dd></div>)}<div><dt>Reference coverage</dt><dd>{selected.count} / {selected.possible} sessions</dd></div></dl>{selected.reason&&<p className="gap-text">{selected.reason}</p>}{snapshot&&<div className="source-detail"><strong>{series?.analyst||series?.label}</strong><p>{snapshot.first_observed_at?`Captured ${snapshot.first_observed_at} · numerical revision date unknown`:`Report ${snapshot.report_date} · model ${snapshot.model_date||snapshot.report_date}`}<br/>Used from {settings.strict?(snapshot.verified_available_date||snapshot.available_date):snapshot.available_date}{snapshot.verified_available_date&&<><br/><SourceLink url={snapshot.availability_evidence_url||''} label={`Archived copy proves availability by ${snapshot.verified_available_at?.slice(0,10)}`}/></>}</p><SourceLink url={snapshot.source_url}/></div>}</>}</section>
        <section className="card detail-card"><h2>Reading the bands</h2><p>The orange line is the actual share price. The other lines show what that day's price would be at the stock's historical forward-P/E levels, using the EPS forecast available on that day.</p><p>Implied price = forward EPS × (historical median P/E ± k × historical P/E standard deviation), where k is 1, 1.5 or 2. The reference window excludes the current day and requires 20 valid prior observations.</p><p>After the latest close, dotted curves show future valuation scenarios. Forecasts, contributors and reference multiples stay frozen at that close while the earnings horizon moves forward. The one-year target uses expected earnings during months 13–24 from the origin. Freshness is checked at the origin. Actual prices stop at the last retained close.</p><p>These scenarios do not assign probabilities to future prices. Missing future fiscal years leave gaps; no later forecast is used to complete them.</p><details><summary>Calculation settings</summary><label>Maximum forecast age<select aria-label="Maximum forecast age" value={settings.maxAge} onChange={e=>update({maxAge:Number(e.target.value)})}>{[30,90,180,365,730].map(v=><option key={v} value={v}>{v} calendar days</option>)}</select></label><label className="check-label"><input type="checkbox" checked={settings.strict} onChange={e=>update({strict:e.target.checked})}/> Require verified availability</label><p className="fine-print">Standard deviation uses the mean and n−1 denominator; bands are centered on the median. Non-positive lower bands are omitted. Prices and EPS use the same split basis.</p></details></section></div>
        <section className="card earnings-card"><div className="chart-heading"><div><h2>Forward earnings through time</h2><p>{overlays?'Selected estimator curves, each with its own definition':viewLabel} · same estimates as the valuation chart</p></div><span className="small-label">{company.currency} PER SHARE</span></div><Chart points={visible} metric="earnings" bands={[]} currency={company.currency} chartKey={chartKey+'-eps'} overlays={overlays}/></section>
      </>}
      {tab==='overview'&&<Overview advanced={advanced} data={data} settings={{...settings,...(!advanced?{compareWindows:false}:{}),asOf}} onChange={update} onExport={saveFile} onOpen={(company,series,window)=>{update({company,series,window,mode:settings.mode==='ensemble'?'ensemble':'single',estimatorIds:company===settings.company?settings.estimatorIds:undefined});setTab('valuation')}}/>}
      {tab==='forecasts'&&<section className="card tab-card"><h2>Original forecast models</h2><p>Each row is a fiscal-year forecast retained from an original document. EPS below is as printed, before any later stock-split adjustment. Select an earnings series on the valuation tab to change this archive.</p><div className="archive-summary"><strong>{series?.label||'No eligible series'}</strong><span>{series?.snapshots.length||0} model documents · latest {latestReport?.report_date||'unavailable'}</span></div><p className="fine-print">{series?.accounting_basis} {series?.coverage_note}</p><div className="table-scroll"><table><thead><tr><th>Report / model</th><th>Fiscal target</th><th className="numeric">EPS as printed</th><th className="numeric">Split-normalized EPS</th><th>Source</th></tr></thead><tbody>{[...(series?.snapshots||[])].reverse().flatMap(s=>s.estimates.map(e=><tr key={`${s.id}-${e.observation_id}`}><td>{s.report_date}<small>{s.first_observed_at?'Captured on this date; revision unknown':`Model ${s.model_date||s.report_date}`}</small></td><td>{e.fiscal_period}<small>Ends {e.fiscal_period_end}</small></td><td className="numeric">{number(e.eps)} {series?.currency}</td><td className="numeric">{number(e.eps/splitFactor(company,s.share_basis_date))}</td><td><SourceLink url={s.source_url} label={`Page ${e.source_page||'—'}`}/></td></tr>))}</tbody></table></div>{!series&&<p className="empty-note">Collected leads do not yet establish an attributable, usable earnings model for this company.</p>}</section>}
      {tab==='outcomes'&&<><ReportedEarnings company={company}/><EpsEvaluation company={company} pilot={data.eps_pilot}/><section className="card tab-card"><h2>Forecasts compared with results</h2><p>The existing Korean revenue pilot uses 180- and 365-day horizons. These selected pairs illustrate historical forecast errors; no analyst ranks have been assigned.</p><div className="table-scroll"><table><thead><tr><th>Analyst</th><th>Fiscal year</th><th>Lead time</th><th className="numeric">Forecast revenue</th><th className="numeric">Actual revenue</th><th className="numeric">Absolute error</th><th>Evidence</th></tr></thead><tbody>{data.revenue_pilot.filter(r=>r.company_id===company.id).map((r,i)=><tr key={i}><td>{r.forecaster}<small>{r.firm}</small></td><td>{r.fiscal_period}</td><td>{r.horizon_days} days</td><td className="numeric">₩{number(Number(r.forecast_revenue_KRW)/1e12)}tn</td><td className="numeric">₩{number(Number(r.actual_revenue_KRW)/1e12)}tn</td><td className="numeric">{number(Number(r.absolute_error_pct))}%</td><td><SourceLink url={r.forecast_source_url} label="Forecast"/><br/><SourceLink url={r.actual_source_url} label="Actual"/></td></tr>)}</tbody></table></div>{!data.revenue_pilot.some(r=>r.company_id===company.id)&&<p className="empty-note">No comparable forecast–actual pairs have been prepared for {company.name} yet.</p>}<p className="fine-print">Latest collected estimate strictly before each cutoff, at most 90 days old at that cutoff. This is a small, selected sample without a matched historical consensus benchmark.</p></section></>}
      {tab==='coverage'&&<><GapMap data={data} settings={{...settings,asOf}} selectedSeries={series?.id||''} onExport={saveFile} onOpen={(company,series,asOf)=>{update({company,series,asOf,mode:'single'});setTab('valuation')}}/><BacktestCoverage report={data.backtest_readiness} onExport={saveFile}/><section className="card tab-card"><h2>What the archive supports</h2><p>Price history and earnings history are separate requirements. Every stock remains selectable even where its forward-earnings coverage is incomplete.</p><div className="table-scroll"><table><thead><tr><th>Company</th><th>Price coverage</th><th>EPS series</th><th>Original models</th><th>Status</th></tr></thead><tbody>{data.companies.map(c=><tr key={c.id}><td><button className="table-company" onClick={()=>{update({company:c.id,series:''});setTab('valuation')}}>{c.name} ↗</button></td><td>{c.prices[0]?.date||'Missing'}<small>to {c.prices.at(-1)?.date||'—'} · {c.prices.length} sessions</small></td><td>{c.series.length}</td><td>{new Set(c.series.flatMap(s=>s.snapshots.map(x=>x.source_sha256))).size}</td><td><span className={`badge ${c.series.length?'partial':'missing'}`}>{c.series.length?'Partial report history':'Earnings history needed'}</span></td></tr>)}</tbody></table></div></section><div className="lower-grid"><section className="card detail-card"><h2>{company.name}: remaining gaps</h2><ul>{company.gaps.map((g,i)=><li key={i}>{g}</li>)}</ul><p>Original forecasts collected: {company.forecast_count}. A forecast count includes different metrics and fiscal years; it is not a count of independent predictions.</p></section><section className="card detail-card"><h2>Next data requirement</h2>{data.access_notes.map((n,i)=><p key={i}>{n}</p>)}<p>The app can accept dated NTM EPS snapshots from an entitled data export. Historical availability, accounting basis, currency and split conventions must accompany the values.</p><button className="text-button" onClick={()=>saveFile('forward-data-coverage.json',JSON.stringify({cutoff:data.cutoff,companies:data.companies.map(c=>({company:c.name,prices:c.prices.length,series:c.series.length,gaps:c.gaps})),requirements:data.access_notes},null,2),'application/json')}>Export coverage report ↓</button></section></div></>}
      <footer className="page-footer"><span>Forward / {tab==='gpu'?'Compute':company.symbol}</span><span>{tab==='gpu'?'Ornn rental index · saved daily observations':advanced?`Research snapshot · ${dateLabel(data.cutoff)} · Source links travel with every model`:'Saved closing prices · not live'}</span></footer>
    </main>
  </div>;
}
