import { contributionCsv } from './ensemble';
import { verifiedFrom } from './engine';
import type { Company, ValuationPoint } from './types';
const number=(v:number|null|undefined)=>v==null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:3}).format(v);
export default function EnsembleAudit({company,selected,points,onExport,onInspect}:{company:Company;selected:ValuationPoint|undefined;points:ValuationPoint[];onExport:(name:string,text:string,type?:string)=>void;onInspect:(p:ValuationPoint)=>void}) {
  const e=selected?.ensemble, changes=points.filter(p=>p.ensemble?.compositionChanged).reverse();
  if(!e)return null;
  const labels=(ids:string[])=>ids.map(id=>company.series.find(s=>s.id===id)?.analyst||id).join(', ')||'None';
  return <section className="card tab-card ensemble-audit">
    <div className="section-heading"><h2>Combined estimate contributors</h2><span>{selected?.date}</span></div>
    <div className="ensemble-stats"><div><span>Included estimators</span><strong>{e.contributors.length}</strong></div><div><span>Contributor age range</span><strong>{e.minAge===null?'—':e.minAge===e.maxAge?`${e.minAge} days`:`${e.minAge}–${e.maxAge} days`}</strong></div><div><span>Forward EPS range</span><strong>{e.minEps===e.maxEps?number(e.minEps):`${number(e.minEps)}–${number(e.maxEps)}`} {company.currency}</strong></div><div><span>EPS disagreement, sample SD</span><strong>{number(e.disagreementStd)} {company.currency}</strong></div></div>
    <p>{e.contributors.length===1?'One eligible contributor on this date. The combined estimate equals that forecast; analyst disagreement cannot be measured.':e.contributors.length===0?'No eligible contributors on this date. The price remains visible and the combined valuation has a gap.':`${e.method==='median'?'Median of':'Equal-weighted mean of'} ${e.contributors.length} independent forecasts.`} Contributor ages are measured from the numerical model date, or the report date when no model date is supplied.</p>
    <p className="fine-print">The EPS range and disagreement above describe differences between analysts on this date. The chart's σ bands describe historical P/E variation. Membership can change through time; this reconstruction is not a fixed historical investment strategy.</p>
    {e.contributors.length>0&&<div className="table-scroll"><table><thead><tr><th>Contributor</th><th>Forward EPS</th><th>{e.method==='mean'?'Weight':'Median treatment'}</th><th>Model / report</th><th>Age</th><th>Evidence</th></tr></thead><tbody>{e.contributors.map(c=><tr key={c.seriesId}><td>{c.analyst}<small>{c.firm}</small></td><td>{number(c.eps)} {company.currency}</td><td>{e.method==='mean'?`${number(100/e.contributors.length)}%`:'One observation'}</td><td>{c.snapshot.model_date||'Not supplied'}<small>Report {c.snapshot.report_date}</small></td><td>{c.age} days<small>From {c.ageBasis} date</small></td><td><a href={c.snapshot.source_url} target="_blank" rel="noreferrer">Original model ↗</a><small>Used from {e.strict?verifiedFrom(c.snapshot):c.snapshot.available_date}<br/>{e.strict?'Verified availability':c.snapshot.availability_basis==='verified_available_at'?'Provider timestamp':'Report-date assumption'}</small></td></tr>)}</tbody></table></div>}
    <details><summary>{e.exclusions.length} excluded series on this date</summary><div className="table-scroll"><table><thead><tr><th>Estimator / series</th><th>Exclusion</th><th>Latest available model</th></tr></thead><tbody>{e.exclusions.map(x=><tr key={x.seriesId}><td>{x.label}</td><td>{x.reason}</td><td>{x.snapshot?.model_date||x.snapshot?.report_date||'None available'}</td></tr>)}</tbody></table></div></details>
    <details><summary>{changes.length} contributor changes in the displayed history</summary><p className="fine-print">Entries and exits reflect selected-model availability, age limits and compatibility. The first supported observation is an entry. Click a date to inspect its full composition.</p><div className="table-scroll"><table><thead><tr><th>Date</th><th>Contributors</th><th>Entered</th><th>Left</th></tr></thead><tbody>{changes.map(p=><tr key={p.date}><td><button className="text-button" onClick={()=>onInspect(p)}>{p.date}</button></td><td>{p.ensemble!.contributors.length}</td><td>{labels(p.ensemble!.added)}</td><td>{labels(p.ensemble!.removed)}</td></tr>)}</tbody></table></div></details>
    <button className="text-button" onClick={()=>onExport(`${company.symbol}-ensemble-contributors.csv`,contributionCsv(points))}>Export contributors and exclusions ↓</button>
  </section>;
}
