import type { Company, EpsPilot } from './types';
import { summarizeAccuracy } from './evaluation';
const number=(v:number|null)=>v===null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:3}).format(v);
export default function EpsEvaluation({company,pilot}:{company:Company;pilot:EpsPilot|undefined}) {
  const pairs=pilot?.pairs.filter(p=>p.company_id===company.id)||[];
  const blocked=pilot?.blocked.filter(p=>p.company_id===company.id)||[];
  const summaries=summarizeAccuracy(pairs);
  return <section className="card tab-card eps-evaluation"><h2>Annual EPS forecasts compared with results</h2><p>Compare the last available forecast at 90, 180 and 365 days before the initial annual results release. Both EPS values use the same split basis. Only explicitly compatible reported diluted EPS enters this pilot.</p><p className="fine-print">Model age at each cutoff is at most {pilot?.max_model_age_at_cutoff_days||90} days. Historical publication timing remains a report-date assumption. Comparable historical consensus benchmarks are missing, and the sample is too small for an analyst ranking.</p>
    <div className="archive-summary"><strong>{pairs.length} comparable pairs for {company.name}</strong><span>{new Set(pairs.map(p=>p.fiscal_period)).size} fiscal years · {new Set(pairs.map(p=>p.analyst)).size} analysts</span></div>
    {summaries.length>0&&<><h3>Errors by estimator and forecast horizon</h3><p className="fine-print">Each row keeps its earnings definition and horizon separate and counts each fiscal year once. Sorted by analyst name, not performance. Positive signed error means the forecast was above the result. Small samples describe these observations; they do not establish predictive skill.</p><div className="table-scroll"><table><thead><tr><th>Estimator / definition</th><th>Horizon</th><th>Independent years</th><th>Mean absolute EPS error</th><th>Mean signed EPS error</th><th>Median absolute % error</th></tr></thead><tbody>{summaries.map((s,i)=><tr key={i}><td>{s.analyst}<small>{s.firm} · {s.basis.replaceAll('_',' ')}</small></td><td>{s.horizon} days</td><td>{s.years}<small>{s.periods.join(', ')}</small></td><td>{number(s.mae)} {s.currency}</td><td>{number(s.bias)} {s.currency}</td><td>{s.medianApe===null?'Unavailable':`${number(s.medianApe)}%`}<small>{s.apeCount} eligible percentage errors</small></td></tr>)}</tbody></table></div></>}
    {pairs.length?<div className="table-scroll"><table><thead><tr><th>Analyst / report</th><th>Fiscal year</th><th>Horizon</th><th className="numeric">Forecast EPS</th><th className="numeric">Actual EPS</th><th className="numeric">Absolute error</th><th>Sources</th></tr></thead><tbody>{pairs.map((p,i)=><tr key={`${p.fiscal_period}-${p.horizon_days}-${p.analyst}-${i}`}><td>{p.analyst}<small>{p.firm} · {p.report_date}</small></td><td>{p.fiscal_period}<small>Results {p.initial_release_date}</small></td><td>{p.horizon_days} days<small>Cutoff {p.cutoff_date}</small></td><td className="numeric">{number(p.forecast_eps)} {p.currency}</td><td className="numeric">{number(p.actual_eps)} {p.currency}</td><td className="numeric">{number(p.absolute_error_eps)} {p.currency}<small>{p.absolute_error_pct===null?'Percentage unavailable':`${number(p.absolute_error_pct)}%`}</small></td><td><a href={p.forecast_source_url} target="_blank" rel="noreferrer">Forecast ↗</a><br/><a href={p.actual_source_url} target="_blank" rel="noreferrer">Initial results ↗</a></td></tr>)}</tbody></table></div>:<p className="empty-note">No comparable EPS pairs meet the definition, publication-date and model-age requirements for this stock yet.</p>}
    {blocked.length>0&&<details><summary>Why {blocked.length} company-year, basis and horizon combinations are excluded</summary><p className="fine-print">An adjusted or unresolved analyst forecast is not automatically comparable with an issuer's non-GAAP definition. These exclusions remain available for review.</p><div className="table-scroll"><table><thead><tr><th>Year</th><th>Horizon</th><th>Actual EPS definition</th><th>Missing requirement</th></tr></thead><tbody>{blocked.map((b,i)=><tr key={i}><td>{b.fiscal_period}</td><td>{b.horizon_days} days</td><td>{b.accounting_basis}</td><td>{b.reason}</td></tr>)}</tbody></table></div></details>}
  </section>;
}
