import { useEffect, useMemo, useRef, useState } from 'react';
import { buildGapMap, gapCsv, reasonLabels } from './coverage';
import type { CoverageRow, GapReason, MonthCoverage } from './coverage';
import type { DashboardData, Settings } from './types';

function status(m:MonthCoverage) {return !m.sessions?'unlisted':m.eps_days===m.sessions?'complete':m.eps_days?'partial':m.other_series_days?'other-series':'missing';}
export default function GapMap({data,settings,selectedSeries,onOpen,onExport}:{data:DashboardData;settings:Settings;selectedSeries:string;onOpen:(company:string,series:string,asOf:string)=>void;onExport:(filename:string,contents:string)=>void}) {
  const [selected,setSelected]=useState<{row:CoverageRow;month:MonthCoverage}|null>(null);
  const [overrides,setOverrides]=useState<Record<string,string>>({[settings.company]:selectedSeries});
  const scroll=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(scroll.current)scroll.current.scrollLeft=scroll.current.scrollWidth},[]);
  const rows=useMemo(()=>buildGapMap(data,settings,overrides),[data,settings.asOf,settings.window,settings.maxAge,settings.strict,overrides]);
  const months=rows[0]?.months.map(m=>m.month)||[];
  const active=selected?{row:rows.find(r=>r.company_id===selected.row.company_id)!,month:rows.find(r=>r.company_id===selected.row.company_id)!.months.find(m=>m.month===selected.month.month)!}:null;
  return <section className="card tab-card gap-map"><div className="section-heading"><div><h2>Forecast gaps by month</h2><p>One selected series per stock. Click a month to inspect its gaps and other available series.</p></div><button className="text-button" onClick={()=>onExport('monthly-forecast-gaps.csv',gapCsv(rows))}>Export gap map ↓</button></div>
    <p className="fine-print">{settings.maxAge}-day model age limit · {settings.window}-day band window · through {settings.asOf}. Colours show usable positive forward EPS. Counts are observed price sessions, with the first and last months limited to this date range.</p>
    <div className="gap-legend"><span><i className="complete"/>All sessions</span><span><i className="partial"/>Some sessions</span><span><i className="other-series"/>Other series only</span><span><i className="missing"/>No usable EPS</span><span><i className="unlisted"/>No prices</span></div>
    <div className="gap-navigation"><button onClick={()=>scroll.current?.scrollTo({left:0})}>← Start of history</button><span>Scroll sideways to explore the full history</span><button onClick={()=>scroll.current?.scrollTo({left:scroll.current.scrollWidth})}>Recent months →</button></div>
    <div className="table-scroll" ref={scroll}><table className="gap-table"><thead><tr><th>Company / earnings series</th>{months.map(m=><th key={m} title={m}><small>{m.slice(2,4)}</small>{m.slice(5)}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.company_id}><td><strong>{row.symbol}</strong><select aria-label={`${row.symbol} gap-map series`} value={row.series_id} onChange={e=>setOverrides(o=>({...o,[row.company_id]:e.target.value}))}>{data.companies.find(c=>c.id===row.company_id)!.series.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}{!row.series_id&&<option value="">No earnings series</option>}</select></td>{row.months.map(m=><td key={m.month}><button className={`gap-cell ${status(m)}`} aria-label={`${row.symbol} ${m.month}: ${m.eps_days} of ${m.sessions} sessions with usable EPS`} title={`${m.month}: ${m.eps_days}/${m.sessions} usable EPS; ${m.band_days} with price bands; ${m.other_series_days} available only in other series`} onClick={()=>setSelected({row,month:m})}>{m.sessions?m.eps_days:'·'}</button></td>)}</tr>)}</tbody></table></div>
    {active&&<div className="gap-inspector"><h3>{active.row.symbol} · {active.month.month}</h3><p>{active.row.series_label}</p><p>{active.month.eps_days} / {active.month.sessions} sessions with usable EPS · {active.month.band_days} with price bands · {active.month.new_models} newly available models.</p><ul>{Object.entries(active.month.reasons).map(([reason,count])=><li key={reason}>{reasonLabels[reason as GapReason]}: {count} sessions</li>)}</ul>{active.month.other_series_days>0&&<p>{active.month.other_series_days} missing sessions have usable estimates in another series. Its author or earnings definition differs; switch the row's series to inspect it separately.</p>}{active.month.eps_days>active.month.band_days&&<p>Some usable EPS dates lack the 20 prior valuation observations required for price bands.</p>}<button onClick={()=>{const [y,m]=active.month.month.split('-').map(Number);const end=new Date(Date.UTC(y,m,0)).toISOString().slice(0,10);onOpen(active.row.company_id,active.row.series_id,end<settings.asOf?end:settings.asOf)}}>Open this stock and month ↗</button></div>}
  </section>;
}
