import type { BacktestReadiness } from './readiness';
export interface Price { date: string; close: number; currency: string; adjustment_basis: string; source_url: string; source_sha256: string }
export interface Split { effective_date: string; ratio: number; source_url: string }
export interface Estimate { observation_id: string; fiscal_period: string; fiscal_period_start: string; fiscal_period_end: string; eps: number; source_page: string; notes?: string; original_accounting_basis?: string; basis_alias_evidence?: string }
export interface Snapshot { id: string; report_date: string; model_date: string; available_date: string; availability_basis: string; first_observed_at?: string; verified_available_date?: string; verified_available_at?: string; availability_evidence_url?: string; verification_kind?: string; share_basis_date: string; source_url: string; source_file: string; source_sha256: string; kind: 'annual' | 'ntm'; estimates: Estimate[] }
export interface Series { compatibility_group?: {id:string;label:string;note:string;evidence_url:string;approved_snapshot_ids:string[]}; series_type?: string; comparability_note?: string; comparability_source_url?: string; id: string; label: string; analyst: string; firm: string; accounting_basis: string; currency: string; coverage_note: string; snapshots: Snapshot[] }
export interface ReportedAnnualEps { period_start:string; period_end:string; value:number; unit:string; accounting_basis:string; filing_date:string; accession:string; source_url:string; source_file:string; source_sha256:string; source_locator:string }
export interface Company { id: string; name: string; symbol: string; exchange: string; currency: string; prices: Price[]; splits: Split[]; series: Series[]; gaps: string[]; forecast_count: number; data_notes?:string[]; reported_earnings?:{annual_eps:ReportedAnnualEps[];notes:string[]} }
export interface Outcome { company_id: string; fiscal_period: string; metric: string; value: string; unit: string; result_version: string; source_url: string; earnings_release_date: string }
export interface Pilot {company_id: string; fiscal_period: string; forecaster: string; firm: string; horizon_days: string; report_date: string; forecast_revenue_KRW: string; actual_revenue_KRW: string; absolute_error_pct: string; forecast_source_url: string; actual_source_url: string}
export interface EpsPair {company_id:string; fiscal_period:string; analyst:string; firm:string; accounting_basis:string; currency:string; horizon_days:number; cutoff_date:string; report_date:string; model_date:string; initial_release_date:string; forecast_eps:number; actual_eps:number; signed_error_eps:number; absolute_error_eps:number; absolute_error_pct:number|null; forecast_source_url:string; actual_source_url:string}
export interface EpsPilot {pairs:EpsPair[];blocked:{company_id:string;fiscal_period:string;horizon_days:number;accounting_basis:string;reason:string}[];ranking_status:string;max_model_age_at_cutoff_days:number;horizon_definition:string}
export interface DashboardData { schema_version: number; generated_at: string; cutoff: string; companies: Company[]; outcomes: Outcome[]; revenue_pilot: Pilot[]; eps_pilot?:EpsPilot; backtest_readiness?:BacktestReadiness; totals: {broker_pdfs: number; forecast_observations: number}; access_notes: string[] }
export type EstimatorMode = 'single' | 'overlay' | 'ensemble';
export type CombineMethod = 'median' | 'mean';
export interface Settings { company: string; series: string; window: number; display: number; maxAge: number; strict: boolean; metric: 'price' | 'multiple'; bands: number[]; asOf: string; mode?: EstimatorMode; combine?: CombineMethod; estimatorIds?: string[]; targetSigma?: number; compareWindows?: boolean; compareWindow?: number; overviewSort?: 'universe'|'name'|'upside'; overviewVersion?: number }
export interface Contribution { seriesId: string; label: string; analyst: string; firm: string; eps: number; age: number; ageBasis: 'model' | 'report'; snapshot: Snapshot }
export interface Exclusion { seriesId: string; label: string; reason: string; snapshot?: Snapshot | null }
export interface EnsembleDetail { strict: boolean; method: CombineMethod; group: string; contributors: Contribution[]; exclusions: Exclusion[]; minAge: number | null; maxAge: number | null; minEps: number | null; maxEps: number | null; disagreementStd: number | null; added: string[]; removed: string[]; compositionChanged: boolean }
export interface ValuationPoint { date: string; price: number; eps: number | null; multiple: number | null; median: number | null; std: number | null; count: number; possible: number; percentile: number | null; z: number | null; snapshot: Snapshot | null; reason: string | null; ensemble?: EnsembleDetail }
